import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar';
import Sidebar from './components/Sidebar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header><Navbar/></header>
        <div className="grid md:grid-cols-2">
          <Sidebar/>
          {children}
        </div>
      </body>
    </html>
  )
}
